# Avoid using the bazel-toolchain crosstools file. For some reason this hinges on whether or not we're building CUDA things...
cuda_compiler_version:
  - "None"

libgrpc:
  - 1.74.1
libabseil:
  - 20250814.1
libprotobuf:
  - 6.33.0